# Generated by Django 5.2.11 on 2026-02-27 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Title must contain only letters and spaces.', regex='^[A-Za-z ]+$')])),
                ('ticker', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ticker must contain only uppercase letters and dots.', regex='^[A-Z\\.]+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolio.portfolio')),
            ],
        ),
    ]
